function [ white_noise_amp, gaussian_amp, gaussian_mean, gaussian_std,...
    sinusoid_amp, sinusoid_freq sinusoid_phase] =...
    recoverWaveformComponents( waveform, deltaT )

% recoverWaveformComponents:
%   Recovers amplitude components from waveforms generated by waveformGen.
%   Written by Steven (Susan) Dorsher on 8/9/13.
%
% This program recovers amplitudes, standard deviation, mean, frequency,
% and phase for a gaussian and sinusoidal waveform with white noise. 
%
% This program:
% -Fourier transforms the data and obtains an Amplitude Spectral Density
% such that the sinusoid becomes a spike and the white noise becomes a 
% flat offset with noise in it.
%
% -Estimates the white_noise_amp by finding the minimum average
% value over some region of the ASD. This is a biased estimator toward
% smaller values, except in the case where the gaussian is still present.
%
%-Determines the maximum and secondary local maximum binned values of the
% ASD, using medium sized bins. 
%
%-Tests the region around each bin to determine if it is a delta function
% or a gaussian peak.
%
% 1) To test if it is a delta function, it looks for a more than 30% drop
% between adjacent pixels relative to the height of the average of two 
% adjacent small bins. A range of 7 pixels is cut if this test is positive, 
% and the seven pixels are 
% replaced by the average value of the two neighboring small bins. 
% 
% 2) To test for a gaussian peak, it determines the Full Width at Half 
% Maximum, binning values into small bins in order to determine this (to
% reduce noise). FWHM = 2.3548 std. Confirm that the empirical quantity of 
% data within this region matches the probability of being within this
% region, using error bars set by the gaussian white noise measurement,
% given the height of the peak.
% This test uses the remainder left over by the delta function test.
%
%-The gaussian_amp is estimated from the height of the peak.
%-The location of the gaussian peak is used to estimate the gaussian_mean.
%-The gaussian_std is estimated from the FWHM.
%-The height of the delta function peak is used to estimate the
% sinusoidal_amp.
%-The location of the delta function peak is used to estimate the
% sinusoidal_freq.
%
%NOTE:
% -Due to the white noise, sinusoidal_phase is irrecoverable by this method.
% Future methods may allow for its development. 
%
%----------------------
% Example:
% waveform = waveformGen(1,5,1,10,1,0.1,0,0.1,1000);
% [wna,ga,gm,gs,sa,sf,sp] = recoverWaveformComponents(waveform,0.1);
%
% This program was developed in the absence of the Fitting Toolbox. A more
% direct approach may be possible in the presence of a maximum likelihood
% fitting function, depending on the details of how it works. 

%-------------------

%Fourier transform and calculate Amplitude spectral density
fftwaveform = fft(waveform); %Fourier transform

%rearrange fft in chronological order
sampleFreq = 1/deltaT;
nyquistFreq = sampleFreq/2;
freqIndex=1:floor(length(fftwaveform)/2+1);
minFreq=nyquistFreq/length(freqIndex);
freqs=freqIndex*minFreq;
fwaveform = fftwaveform(freqIndex);

ASD = sqrt(fwaveform.*conj(fwaveform)); %amplitude spectral density
%discard phase information due to white noise

%------------------------
%Calculate white noise amplitude
white_noise_amp=estimateWhiteNoise(ASD);

%search for a sinusoidal delta function peak in the ASD
[sinusoid_amp sinusoid_freq sinusoid_phase] = ...
    getSinParams(minFreq,ASD,white_noise_amp);

%plot(freqs,ASD)   

%cut the sinusoidal peaks from the data

%---------------
%Determine the maximum and secondary local maximum of binned values of the
% ASD, using intermediate sized bins. 

%numPerIBin = 5;
%ASDIbinned = binASD(numPerIBin, ASD);

%search averages of regions for greatest and second greatest local maximum
%[max1index max2index] = getTwolocalMaxima(ASDIbinned);

%-------------
%Determination of sinusoid parameters

%tests the region around the tallest maximum to determine if it is a delta
%function

%if so, determines sinusoid parameters

%and cuts the region around delta function peaks

%if it is not, tests the region around the other maximum to determine if
% it is a delta function

%if so, determines sinusoid parameters

%and cuts the region around delta function peaks

%if not, returns zeros

%returns zero for sinusoid phase-- not yet developed

%------------
%Determination of Gaussian parameters

%tests the region around tallest unidentified peak to determine if it is 
%a gaussian

%determines the gaussian parameters if the peak is identified

%if not, returns zeros

%---------------------

gaussian_amp = 0;
gaussian_mean = 0;
gaussian_std = 0;

end

